//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TellMeWYS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TellMeWYS.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add member.
        /// </summary>
        public static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Name.
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Port.
        /// </summary>
        public static string ClientPort {
            get {
                return ResourceManager.GetString("ClientPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Channel.
        /// </summary>
        public static string CreateChannel {
            get {
                return ResourceManager.GetString("CreateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this channel.
        /// </summary>
        public static string DeleteThisChannel {
            get {
                return ResourceManager.GetString("DeleteThisChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit channel name.
        /// </summary>
        public static string EditChannelName {
            get {
                return ResourceManager.GetString("EditChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s this site?
        ///-----------------
        ///
        ///This site aimed at helping telefhone supporter for your web site.
        ///
        ///You can get the URL that your customer on your web site visiting now via this site by customer&apos;s action..
        /// </summary>
        public static string Home_Description {
            get {
                return ResourceManager.GetString("Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Your Channel List.
        /// </summary>
        public static string Home_GotoChannelList {
            get {
                return ResourceManager.GetString("Home_GotoChannelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to try?
        ///-----------
        ///
        ///At first, sign in this site, and create &quot;Channel&quot;.
        ///
        ///After this, open &quot;Channel&quot; page, then you can see &quot;Open Test Drive Page&quot; link.
        ///
        ///click &quot;Open Test Drive Page&quot; link to open the test drive page in new tab or window..
        /// </summary>
        public static string Home_HowToTry {
            get {
                return ResourceManager.GetString("Home_HowToTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation
        ///-----------
        ///1. Sign in with Microsoft or Google account. (It&apos;s Free, No purchase.)
        ///2. Create &quot;Channel&quot;, and get the URL of the JavaScript file that provide small function at settings page.
        ///3. Embed the including the JavaScript file that you got at &quot;Channel&quot; setting page into your web site,
        ///4. and handle the click event any UI element (such as &quot;Help Me!&quot; button) and call &quot;window.tellMeWYS.sendUrl()&quot;..
        /// </summary>
        public static string Home_Preparation {
            get {
                return ResourceManager.GetString("Home_Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In / Sign Up (Free).
        /// </summary>
        public static string Home_SignIn_SignUp {
            get {
                return ResourceManager.GetString("Home_SignIn_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage
        ///-----
        ///One day, when you recieve the call from your customers to help them...
        ///
        ///1. Sign in this site and open &quot;Channel&quot; page for listen to the messages from your web site.
        ///2. Ask them to click the UI elemet that you wired up the code of calling &quot;sendUrl&quot; method.
        ///3. If your customer click the elemnt, and fire &quot;window.tellMeWYS.sendUrl()&quot;, then the URL ot the page that your customer opend now appear at &quot;Channel&quot; page!
        ///4.You can click the URL on &quot;Channel&quot; page, then open the web page that the same o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Usage {
            get {
                return ResourceManager.GetString("Home_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Library.
        /// </summary>
        public static string JavaScriptLibrary {
            get {
                return ResourceManager.GetString("JavaScriptLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, you can call follow JavaScript code..
        /// </summary>
        public static string JS_Example_Call {
            get {
                return ResourceManager.GetString("JS_Example_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include JavaScript into your web site like this:.
        /// </summary>
        public static string JS_Example_IncludeJavaScriptLikeThis {
            get {
                return ResourceManager.GetString("JS_Example_IncludeJavaScriptLikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to sample page {0}.
        /// </summary>
        public static string JumpToSamplePage {
            get {
                return ResourceManager.GetString("JumpToSamplePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening messages....
        /// </summary>
        public static string ListeningMessages {
            get {
                return ResourceManager.GetString("ListeningMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Title).
        /// </summary>
        public static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Test Drive page.
        /// </summary>
        public static string OpenTestDrivePage {
            get {
                return ResourceManager.GetString("OpenTestDrivePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other actions.
        /// </summary>
        public static string OtherActions {
            get {
                return ResourceManager.GetString("OtherActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove member.
        /// </summary>
        public static string RemoveMember {
            get {
                return ResourceManager.GetString("RemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send URL.
        /// </summary>
        public static string SendURL {
            get {
                return ResourceManager.GetString("SendURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Me WYS.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure?.
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Drive Page.
        /// </summary>
        public static string TestDrivePage {
            get {
                return ResourceManager.GetString("TestDrivePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is sample page {0}.
        /// </summary>
        public static string ThisIsSamplePage {
            get {
                return ResourceManager.GetString("ThisIsSamplePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Channels.
        /// </summary>
        public static string YourChannels {
            get {
                return ResourceManager.GetString("YourChannels", resourceCulture);
            }
        }
    }
}
